[build]
  command = "npm run build"
  functions = "dist/functions"

[functions]
  external_node_modules = ["mongoose"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
